#ifndef APPLICATIONSERVERODATAPLUGIN_GLOBAL_H
#define APPLICATIONSERVERODATAPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(APPLICATIONSERVERODATAPLUGIN_LIBRARY)
#  define APPLICATIONSERVERODATAPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define APPLICATIONSERVERODATAPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // APPLICATIONSERVERODATAPLUGIN_GLOBAL_H
